# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calckernelc <- function(x, k, row, col) {
    .Call(`_gridkernel_calckernelc`, x, k, row, col)
}

kernelsmoothc <- function(x, k) {
    .Call(`_gridkernel_kernelsmoothc`, x, k)
}

upscalec <- function(x, factor, maxPNA) {
    .Call(`_gridkernel_upscalec`, x, factor, maxPNA)
}

